[package]
name = "korangar-video"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
libc = { workspace = true }
rav1d = { workspace = true }
