on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

# Cancel previous jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Lint

env:
  CARGO_TERM_COLOR: always
  SLANG_VERSION: v2025.17.2

jobs:
  clippy:
    name: Run cargo clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt install libasound2-dev nasm

      - name: Cache slangc
        id: cache-slangc
        uses: actions/cache@v4
        with:
          path: ~/slangc
          key: ${{ runner.os }}-slangc-${{ env.SLANG_VERSION }}

      - name: Download and install slangc
        if: steps.cache-slangc.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/slangc
          cd ~/slangc
          
          VERSION_NO_V=${SLANG_VERSION#v}
          curl -L -o slang-linux-x86_64.tar.gz \
            "https://github.com/shader-slang/slang/releases/download/${{ env.SLANG_VERSION }}/slang-${VERSION_NO_V}-linux-x86_64.tar.gz"
          
          tar -xzf slang-linux-x86_64.tar.gz
          rm slang-linux-x86_64.tar.gz
          
          chmod +x bin/slangc bin/slangd

      - name: Add slangc to PATH
        run: echo "$HOME/slangc/bin" >> $GITHUB_PATH

      - name: Verify slangc installation
        run: |
          which slangc
          slangc -version

      - name: Add Clippy
        run: rustup component add clippy

      - name: Run Clippy (default features)
        run: cargo clippy -- -Dwarnings

      - name: Run Clippy (all features)
        run: cargo clippy --all-features -- -Dwarnings

  flake-nix:
    name: flake.nix linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake.nix
        run: nix flake check -L --all-systems
